@startuml

class Operation {
    private String operation_;

    public Operation(); 
    public String getOperation();
    public void setOperation(String operation);
}

class MathematicalOperation {
    private double result_;

    public MathematicalOperation();
    public void solve(String operation) throws OperationException;
    public String toString();
} 

class Calculator {

    public Calculator();
    public void solve(String operation);
    public String toString();
} 

Operation <|-down- MathematicalOperation: Inheritance
Calculator "1" *-up- "1" MathematicalOperation: operation

@enduml